[package]
name = "common-mem-allocator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../base" }
common-infallible = { path = "../infallible" }
libc = "0.2"

parking_lot = "0.12.0"
tikv-jemalloc-ctl = "0.4"
tikv-jemalloc-sys = { version = "0.4.3", features = ["stats", "profiling", "unprefixed_malloc_on_supported_platforms"] }

[dev-dependencies]
common-macros = { path = "../macros" }
